In [ ]:
from google.colab import files
uploaded= files.upload()
import pandas as pd
df=pd.read_csv("songs_db.csv")
df.head()

Saving songs_db.csv to songs_db (1).csv

,title,artist,movie,language,emotion
0,Samajavaragamana,Sid Sriram,Ala Vaikunthapurramuloo,Telugu,Joy
1,Butta Bomma,Armaan Malik,Ala Vaikunthapurramuloo,Telugu,Trust
2,Srivalli,Sid Sriram,Pushpa,Telugu,Anticipation
3,Oo Antava,Indravathi Chauhan,Pushpa,Telugu,Joy
4,Leharaayi,Haricharan,Most Eligible Bachelor,Telugu,Trust

In [ ]:
from google.colab import files
uploaded= files.upload()
import pandas as pd
df=pd.read_csv("songs_db.csv")
df = df.fillna(df.mean)
df = df.fillna(df.median)
df = df.fillna(df.mode)

Saving songs_db.csv to songs_db (6).csv

In [ ]:
from google.colab import files
uploaded= files.upload()
import pandas as pd
df=pd.read_csv("songs_db.csv")
df.isnull().sum()

Saving songs_db.csv to songs_db (5).csv

title       0
artist      0
movie       0
language    0
emotion     0
dtype: int64

In [ ]:
from google.colab import files
uploaded= files.upload()
import pandas as pd
df=pd.read_csv("songs_db.csv")
print('rows: ', df.shape[0])
print('columns: ', df.shape[1])

Saving songs_db.csv to songs_db (4).csv
rows:  101
columns:  5

In [ ]:
from google.colab import files
uploaded= files.upload()
import pandas as pd
df=pd.read_csv("songs_db.csv")
df.tail()

Saving songs_db.csv to songs_db (2).csv

            title         artist             movie language       emotion
96     Levitating       Dua Lipa  Future Nostalgia  English           Joy
97        Peaches  Justin Bieber           Justice  English          Love
98      As It Was   Harry Styles     Harry's House  English       Sadness
99        Shivers     Ed Sheeran                 =  English          Love
100  Viva La Vida       Coldplay      Viva La Vida  English  Anticipation